var dir_bc51459744ca053627febfa3e02ec663 =
[
    [ "GLARBDepthTexture.d", "_g_l_a_r_b_depth_texture_8d.html", null ],
    [ "GLARBDrawBuffers.d", "_g_l_a_r_b_draw_buffers_8d.html", null ],
    [ "GLARBDrawInstanced.d", "_g_l_a_r_b_draw_instanced_8d.html", null ],
    [ "GLARBFragmentProgram.d", "_g_l_a_r_b_fragment_program_8d.html", null ],
    [ "GLARBFragmentShader.d", "_g_l_a_r_b_fragment_shader_8d.html", null ],
    [ "GLARBGeometryShader4.d", "_g_l_a_r_b_geometry_shader4_8d.html", null ],
    [ "GLARBMultitexture.d", "_g_l_a_r_b_multitexture_8d.html", null ],
    [ "GLARBPointParameters.d", "_g_l_a_r_b_point_parameters_8d.html", null ],
    [ "GLARBPointSprite.d", "_g_l_a_r_b_point_sprite_8d.html", null ],
    [ "GLARBShaderObjects.d", "_g_l_a_r_b_shader_objects_8d.html", null ],
    [ "GLARBShadow.d", "_g_l_a_r_b_shadow_8d.html", null ],
    [ "GLARBTextureCompression.d", "_g_l_a_r_b_texture_compression_8d.html", null ],
    [ "GLARBTextureFloat.d", "_g_l_a_r_b_texture_float_8d.html", null ],
    [ "GLARBTextureNonPowerOfTwo.d", "_g_l_a_r_b_texture_non_power_of_two_8d.html", null ],
    [ "GLARBTextureRectangle.d", "_g_l_a_r_b_texture_rectangle_8d.html", null ],
    [ "GLARBTextureRg.d", "_g_l_a_r_b_texture_rg_8d.html", null ],
    [ "GLARBVertexBufferObject.d", "_g_l_a_r_b_vertex_buffer_object_8d.html", null ],
    [ "GLARBVertexProgram.d", "_g_l_a_r_b_vertex_program_8d.html", null ],
    [ "GLARBVertexShader.d", "_g_l_a_r_b_vertex_shader_8d.html", null ],
    [ "GLEXTFramebufferBlit.d", "_g_l_e_x_t_framebuffer_blit_8d.html", null ],
    [ "GLEXTFramebufferObject.d", "_g_l_e_x_t_framebuffer_object_8d.html", null ],
    [ "GLEXTGeometryShader4.d", "_g_l_e_x_t_geometry_shader4_8d.html", null ],
    [ "GLEXTPalettedTexture.d", "_g_l_e_x_t_paletted_texture_8d.html", null ],
    [ "GLEXTRescaleNormal.d", "_g_l_e_x_t_rescale_normal_8d.html", null ],
    [ "GLEXTTexture3D.d", "_g_l_e_x_t_texture3_d_8d.html", null ],
    [ "GLEXTTextureCompressionS3TC.d", "_g_l_e_x_t_texture_compression_s3_t_c_8d.html", null ],
    [ "GLEXTTextureCubeMap.d", "_g_l_e_x_t_texture_cube_map_8d.html", null ],
    [ "GLNVFogDistance.d", "_g_l_n_v_fog_distance_8d.html", null ],
    [ "GLNVOcclusionQuery.d", "_g_l_n_v_occlusion_query_8d.html", null ],
    [ "GLNVPointSprite.d", "_g_l_n_v_point_sprite_8d.html", null ],
    [ "GLNVTextureShader.d", "_g_l_n_v_texture_shader_8d.html", null ]
];