var namespace_geometry =
[
    [ "Ray", "class_geometry_1_1_ray.html", "class_geometry_1_1_ray" ],
    [ "Point", "class_geometry_1_1_point.html", "class_geometry_1_1_point" ],
    [ "Vector", "class_geometry_1_1_vector.html", "class_geometry_1_1_vector" ],
    [ "Rotation", "class_geometry_1_1_rotation.html", "class_geometry_1_1_rotation" ],
    [ "OrthonormalTransformation", "class_geometry_1_1_orthonormal_transformation.html", "class_geometry_1_1_orthonormal_transformation" ],
    [ "OrthogonalTransformation", "class_geometry_1_1_orthogonal_transformation.html", "class_geometry_1_1_orthogonal_transformation" ],
    [ "Geoid", "class_geometry_1_1_geoid.html", "class_geometry_1_1_geoid" ],
    [ "AffineCombiner", "class_geometry_1_1_affine_combiner.html", "class_geometry_1_1_affine_combiner" ],
    [ "AffineTransformationOperations", "class_geometry_1_1_affine_transformation_operations.html", "class_geometry_1_1_affine_transformation_operations" ],
    [ "AffineTransformationOperations< ScalarParam, 2 >", "class_geometry_1_1_affine_transformation_operations_3_01_scalar_param_00_012_01_4.html", "class_geometry_1_1_affine_transformation_operations_3_01_scalar_param_00_012_01_4" ],
    [ "AffineTransformationOperations< ScalarParam, 3 >", "class_geometry_1_1_affine_transformation_operations_3_01_scalar_param_00_013_01_4.html", "class_geometry_1_1_affine_transformation_operations_3_01_scalar_param_00_013_01_4" ],
    [ "TranslationTransformation", "class_geometry_1_1_translation_transformation.html", "class_geometry_1_1_translation_transformation" ],
    [ "RotationTransformation", "class_geometry_1_1_rotation_transformation.html", "class_geometry_1_1_rotation_transformation" ],
    [ "UniformScalingTransformation", "class_geometry_1_1_uniform_scaling_transformation.html", "class_geometry_1_1_uniform_scaling_transformation" ],
    [ "ScalingTransformation", "class_geometry_1_1_scaling_transformation.html", "class_geometry_1_1_scaling_transformation" ],
    [ "AffineTransformation", "class_geometry_1_1_affine_transformation.html", "class_geometry_1_1_affine_transformation" ],
    [ "AlbersEqualAreaProjection", "class_geometry_1_1_albers_equal_area_projection.html", "class_geometry_1_1_albers_equal_area_projection" ],
    [ "ArrayKdTree", "class_geometry_1_1_array_kd_tree.html", "class_geometry_1_1_array_kd_tree" ],
    [ "Box", "class_geometry_1_1_box.html", "class_geometry_1_1_box" ],
    [ "BSpline", "class_geometry_1_1_b_spline.html", "class_geometry_1_1_b_spline" ],
    [ "ClosePointSet", "class_geometry_1_1_close_point_set.html", "class_geometry_1_1_close_point_set" ],
    [ "ComponentArray", "class_geometry_1_1_component_array.html", "class_geometry_1_1_component_array" ],
    [ "ComponentArray< ScalarParam, 2 >", "class_geometry_1_1_component_array_3_01_scalar_param_00_012_01_4.html", "class_geometry_1_1_component_array_3_01_scalar_param_00_012_01_4" ],
    [ "ComponentArray< ScalarParam, 3 >", "class_geometry_1_1_component_array_3_01_scalar_param_00_013_01_4.html", "class_geometry_1_1_component_array_3_01_scalar_param_00_013_01_4" ],
    [ "ComponentArray< ScalarParam, 4 >", "class_geometry_1_1_component_array_3_01_scalar_param_00_014_01_4.html", "class_geometry_1_1_component_array_3_01_scalar_param_00_014_01_4" ],
    [ "Cone", "class_geometry_1_1_cone.html", "class_geometry_1_1_cone" ],
    [ "Cylinder", "class_geometry_1_1_cylinder.html", "class_geometry_1_1_cylinder" ],
    [ "HVector", "class_geometry_1_1_h_vector.html", "class_geometry_1_1_h_vector" ],
    [ "Matrix", "class_geometry_1_1_matrix.html", "class_geometry_1_1_matrix" ],
    [ "ValuedPoint", "class_geometry_1_1_valued_point.html", "class_geometry_1_1_valued_point" ],
    [ "GeoCoordinateSystem", "class_geometry_1_1_geo_coordinate_system.html", "class_geometry_1_1_geo_coordinate_system" ],
    [ "GeoReprojector", "class_geometry_1_1_geo_reprojector.html", "class_geometry_1_1_geo_reprojector" ],
    [ "Plane", "class_geometry_1_1_plane.html", "class_geometry_1_1_plane" ],
    [ "ProjectiveTransformation", "class_geometry_1_1_projective_transformation.html", "class_geometry_1_1_projective_transformation" ],
    [ "HitResult", "class_geometry_1_1_hit_result.html", "class_geometry_1_1_hit_result" ],
    [ "LambertConformalProjection", "class_geometry_1_1_lambert_conformal_projection.html", "class_geometry_1_1_lambert_conformal_projection" ],
    [ "LinearInterpolator", "class_geometry_1_1_linear_interpolator.html", "class_geometry_1_1_linear_interpolator" ],
    [ "LinearInterpolator< ComponentArray< ScalarParam, dimensionParam > >", "class_geometry_1_1_linear_interpolator_3_01_component_array_3_01_scalar_param_00_01dimension_param_01_4_01_4.html", "class_geometry_1_1_linear_interpolator_3_01_component_array_3_01_scalar_param_00_01dimension_param_01_4_01_4" ],
    [ "LinearInterpolator< Point< ScalarParam, dimensionParam > >", "class_geometry_1_1_linear_interpolator_3_01_point_3_01_scalar_param_00_01dimension_param_01_4_01_4.html", "class_geometry_1_1_linear_interpolator_3_01_point_3_01_scalar_param_00_01dimension_param_01_4_01_4" ],
    [ "LinearInterpolator< Vector< ScalarParam, dimensionParam > >", "class_geometry_1_1_linear_interpolator_3_01_vector_3_01_scalar_param_00_01dimension_param_01_4_01_4.html", "class_geometry_1_1_linear_interpolator_3_01_vector_3_01_scalar_param_00_01dimension_param_01_4_01_4" ],
    [ "LinearInterpolator< HVector< ScalarParam, dimensionParam > >", "class_geometry_1_1_linear_interpolator_3_01_h_vector_3_01_scalar_param_00_01dimension_param_01_4_01_4.html", "class_geometry_1_1_linear_interpolator_3_01_h_vector_3_01_scalar_param_00_01dimension_param_01_4_01_4" ],
    [ "LinearInterpolator< Rotation< ScalarParam, 2 > >", "class_geometry_1_1_linear_interpolator_3_01_rotation_3_01_scalar_param_00_012_01_4_01_4.html", "class_geometry_1_1_linear_interpolator_3_01_rotation_3_01_scalar_param_00_012_01_4_01_4" ],
    [ "LinearInterpolator< Rotation< ScalarParam, 3 > >", "class_geometry_1_1_linear_interpolator_3_01_rotation_3_01_scalar_param_00_013_01_4_01_4.html", "class_geometry_1_1_linear_interpolator_3_01_rotation_3_01_scalar_param_00_013_01_4_01_4" ],
    [ "LinearUnit", "class_geometry_1_1_linear_unit.html", "class_geometry_1_1_linear_unit" ],
    [ "MatrixOperations", "class_geometry_1_1_matrix_operations.html", null ],
    [ "MatrixOperations< ScalarParam, dimensionParam, dimensionParam >", "class_geometry_1_1_matrix_operations_3_01_scalar_param_00_01dimension_param_00_01dimension_param_01_4.html", null ],
    [ "MatrixOperations< ScalarParam, 2, 2 >", "class_geometry_1_1_matrix_operations_3_01_scalar_param_00_012_00_012_01_4.html", null ],
    [ "MatrixOperations< ScalarParam, 3, 3 >", "class_geometry_1_1_matrix_operations_3_01_scalar_param_00_013_00_013_01_4.html", null ],
    [ "PCACalculator", "class_geometry_1_1_p_c_a_calculator.html", "class_geometry_1_1_p_c_a_calculator" ],
    [ "PCACalculator< 2 >", "class_geometry_1_1_p_c_a_calculator_3_012_01_4.html", "class_geometry_1_1_p_c_a_calculator_3_012_01_4" ],
    [ "PCACalculator< 3 >", "class_geometry_1_1_p_c_a_calculator_3_013_01_4.html", "class_geometry_1_1_p_c_a_calculator_3_013_01_4" ],
    [ "PointKdTree", "class_geometry_1_1_point_kd_tree.html", "class_geometry_1_1_point_kd_tree" ],
    [ "PointOctree", "class_geometry_1_1_point_octree.html", "class_geometry_1_1_point_octree" ],
    [ "PointPicker", "class_geometry_1_1_point_picker.html", "class_geometry_1_1_point_picker" ],
    [ "PointTwoNTree", "class_geometry_1_1_point_two_n_tree.html", "class_geometry_1_1_point_two_n_tree" ],
    [ "PolygonBase", "class_geometry_1_1_polygon_base.html", "class_geometry_1_1_polygon_base" ],
    [ "Polygon", "class_geometry_1_1_polygon.html", "class_geometry_1_1_polygon" ],
    [ "Polygon< ScalarParam, 2 >", "class_geometry_1_1_polygon_3_01_scalar_param_00_012_01_4.html", "class_geometry_1_1_polygon_3_01_scalar_param_00_012_01_4" ],
    [ "PolygonMeshVertex", "class_geometry_1_1_polygon_mesh_vertex.html", "class_geometry_1_1_polygon_mesh_vertex" ],
    [ "PolygonMeshEdge", "class_geometry_1_1_polygon_mesh_edge.html", "class_geometry_1_1_polygon_mesh_edge" ],
    [ "PolygonMeshFace", "class_geometry_1_1_polygon_mesh_face.html", "class_geometry_1_1_polygon_mesh_face" ],
    [ "PolygonMeshBaseVertex", "class_geometry_1_1_polygon_mesh_base_vertex.html", "class_geometry_1_1_polygon_mesh_base_vertex" ],
    [ "PolygonMeshVertex< ScalarParam, dimensionParam, void, EdgeDataParam, FaceDataParam >", "class_geometry_1_1_polygon_mesh_vertex_3_01_scalar_param_00_01dimension_param_00_01void_00_01_ed33f6a93160c9bb4480c9406d5c795f4b.html", null ],
    [ "PolygonMeshBaseEdge", "class_geometry_1_1_polygon_mesh_base_edge.html", "class_geometry_1_1_polygon_mesh_base_edge" ],
    [ "PolygonMeshEdge< ScalarParam, dimensionParam, VertexDataParam, void, FaceDataParam >", "class_geometry_1_1_polygon_mesh_edge_3_01_scalar_param_00_01dimension_param_00_01_vertex_data_pa6f4327ba05cdde5d1c803f472ed9f21d.html", null ],
    [ "PolygonMeshBaseFace", "class_geometry_1_1_polygon_mesh_base_face.html", "class_geometry_1_1_polygon_mesh_base_face" ],
    [ "PolygonMeshFace< ScalarParam, dimensionParam, VertexDataParam, EdgeDataParam, void >", "class_geometry_1_1_polygon_mesh_face_3_01_scalar_param_00_01dimension_param_00_01_vertex_data_pab08a27d64f0631fc2ca2326063a07515.html", null ],
    [ "PolygonMesh", "class_geometry_1_1_polygon_mesh.html", "class_geometry_1_1_polygon_mesh" ],
    [ "ProjectiveTransformationOperationsBase", "class_geometry_1_1_projective_transformation_operations_base.html", null ],
    [ "ProjectiveTransformationOperations", "class_geometry_1_1_projective_transformation_operations.html", null ],
    [ "ProjectiveTransformationOperations< ScalarParam, 2 >", "class_geometry_1_1_projective_transformation_operations_3_01_scalar_param_00_012_01_4.html", null ],
    [ "ProjectiveTransformationOperations< ScalarParam, 3 >", "class_geometry_1_1_projective_transformation_operations_3_01_scalar_param_00_013_01_4.html", null ],
    [ "RayPicker", "class_geometry_1_1_ray_picker.html", "class_geometry_1_1_ray_picker" ],
    [ "Rotation< ScalarParam, 2 >", "class_geometry_1_1_rotation_3_01_scalar_param_00_012_01_4.html", "class_geometry_1_1_rotation_3_01_scalar_param_00_012_01_4" ],
    [ "Rotation< ScalarParam, 3 >", "class_geometry_1_1_rotation_3_01_scalar_param_00_013_01_4.html", "class_geometry_1_1_rotation_3_01_scalar_param_00_013_01_4" ],
    [ "SolidHitResult", "class_geometry_1_1_solid_hit_result.html", "class_geometry_1_1_solid_hit_result" ],
    [ "Sphere", "class_geometry_1_1_sphere.html", "class_geometry_1_1_sphere" ],
    [ "SplineCurve", "class_geometry_1_1_spline_curve.html", "class_geometry_1_1_spline_curve" ],
    [ "SplineFitter", "class_geometry_1_1_spline_fitter.html", "class_geometry_1_1_spline_fitter" ],
    [ "SplinePatch", "class_geometry_1_1_spline_patch.html", "class_geometry_1_1_spline_patch" ],
    [ "TransverseMercatorProjection", "class_geometry_1_1_transverse_mercator_projection.html", "class_geometry_1_1_transverse_mercator_projection" ],
    [ "UTMProjection", "class_geometry_1_1_u_t_m_projection.html", "class_geometry_1_1_u_t_m_projection" ],
    [ "ValuedPoint< PointParam, void >", "class_geometry_1_1_valued_point_3_01_point_param_00_01void_01_4.html", "class_geometry_1_1_valued_point_3_01_point_param_00_01void_01_4" ]
];